datasets:
  - name: "Hospital Billing"
    dataset_normalizer: "StandardXes"
    dataset_loader: "RemoteZippedXesGz"
    data_path: "https://data.4tu.nl/ndownloader/items/6af6d5f0-f44c-49be-aac8-8eaa5fe4f6fd/versions/1"
    is_remote: true
    data_owner: "Felix Mannhardt"
    tasks:
      - name: "test_task"

benchmark:
    name: "Test Benchmark"
    save_folder: "test_benchmark"
    tasks:
      - name: "test_task"
        save_folder: "test_benchmark/test_task"
        category: "none"
        metrics:
          - name: "Accuracy"
        task_generator:
          name: "SimpleClassificationGenerator"