datasets:
  - name: "bpi_2019"
    dataset_normalizer: "BPI2019Normalizer"
    dataset_loader: "RemoteXes"
    data_path: "https://data.4tu.nl/file/35ed7122-966a-484e-a0e1-749b64e3366d/864493d1-3a58-47f6-ad6f-27f95f995828"
    is_remote: true
    data_owner: "Boudewijn van Dongen"
  - name: "bpi_2017"
    dataset_normalizer: "BPI2017Normalizer"
    dataset_loader: "RemoteZippedXesGz"
    data_path: "https://data.4tu.nl/ndownloader/items/34c3f44b-3101-4ea9-8281-e38905c68b8d/versions/1"
    is_remote: true
    data_owner: "Boudewijn van Dongen"
  - name: "bpi_2015_1"
    dataset_normalizer: "BPI2015Normalizer"
    dataset_loader: "RemoteXes"
    data_path: "https://data.4tu.nl/file/6f35269e-4ce7-4bc4-9abb-b3cea04cad00/2c8d5827-3e08-471d-98e2-6ffdec92f958"
    is_remote: true
    data_owner: "Boudewijn van Dongen"
  - name: "bpi_2015_2"
    dataset_normalizer: "BPI2015Normalizer"
    dataset_loader: "RemoteXes"
    data_path: "https://data.4tu.nl/file/372d0cad-3fb1-4627-8ea9-51a09923d331/d653a8ec-4cd1-4029-8b61-6cfde4f4a666"
    is_remote: true
    data_owner: "Boudewijn van Dongen"
  - name: "bpi_2015_3"
    dataset_normalizer: "BPI2015Normalizer"
    dataset_loader: "RemoteXes"
    data_path: "https://data.4tu.nl/file/d6741425-5f62-4a59-92c5-08bae64b4611/21b574ab-02ba-4dfb-badc-bb46ce0edc44"
    is_remote: true
    data_owner: "Boudewijn van Dongen"
  - name: "bpi_2015_4"
    dataset_normalizer: "BPI2015Normalizer"
    dataset_loader: "RemoteXes"
    data_path: "https://data.4tu.nl/file/34216d8a-f054-46d4-bf03-d9352f90967e/68923819-b085-43be-abe2-e084a0f1381f"
    is_remote: true
    data_owner: "Boudewijn van Dongen"
  - name: "bpi_2015_5"
    dataset_normalizer: "BPI2015Normalizer"
    dataset_loader: "RemoteXes"
    data_path: "https://data.4tu.nl/file/32b70553-0765-4808-b155-aa5319802c8a/d39e1365-e4b8-4cb8-83d3-0b01cbf6f8c2"
    is_remote: true
    data_owner: "Boudewijn van Dongen"
  - name: "bpi_2012"
    dataset_normalizer: "BPI2012Normalizer"
    dataset_loader: "RemoteZippedXesGz"
    data_path: "https://data.4tu.nl/ndownloader/items/533f66a4-8911-4ac7-8612-1235d65d1f37/versions/1"
    is_remote: true
    data_owner: "Boudewijn van Dongen"
  - name: "bpi_2016"
    dataset_normalizer: "BPI2016Normalizer"
    dataset_loader: "BPI2016Loader"
    data_path: "https://data.4tu.nl/collections/BPI_Challenge_2016/5065538"
    is_remote: true
    data_owner: "Marcus Dees & Boudewijn van Dongen"
  - name: "bpi_2020_domestic"
    dataset_normalizer: "BPI2020Normalizer"
    dataset_loader: "RemoteZippedXesGz"
    data_path: "https://data.4tu.nl/ndownloader/items/6a0a26d2-82d0-4018-b1cd-89afb0e8627f/versions/1"
    is_remote: true
    data_owner: "Boudewijn van Dongen"
  - name: "bpi_2020_international"
    dataset_normalizer: "BPI2020Normalizer"
    dataset_loader: "RemoteZippedXesGz"
    data_path: "https://data.4tu.nl/ndownloader/items/91fd1fa8-4df4-4b1a-9a3f-0116c412378f/versions/1"
    is_remote: true
    data_owner: "Boudewijn van Dongen"
  - name: "bpi_2020_travel_cost"
    dataset_normalizer: "BPI2020Normalizer"
    dataset_loader: "RemoteZippedXesGz"
    data_path: "https://data.4tu.nl/ndownloader/items/fb84cf2d-166f-4de2-87be-62ee317077e5/versions/1"
    is_remote: true
    data_owner: "Boudewijn van Dongen"
  - name: "bpi_2020_rfp"
    dataset_normalizer: "BPI2020Normalizer"
    dataset_loader: "RemoteZippedXesGz"
    data_path: "https://data.4tu.nl/ndownloader/items/a6f651a7-5ce0-4bc6-8be1-a7747effa1cc/versions/1"
    is_remote: true
    data_owner: "Boudewijn van Dongen"
  - name: "bpi_2020_permits"
    dataset_normalizer: "BPI2020Normalizer"
    dataset_loader: "RemoteZippedXesGz"
    data_path: "https://data.4tu.nl/ndownloader/items/db35afac-2133-40f3-a565-2dc77a9329a3/versions/1"
    is_remote: true
    data_owner: "Boudewijn van Dongen"