datasets:
  - name: "bpi_2019"
    dataset_normalizer: "BPI2019Normalizer"
    dataset_loader: "LocalXes"
    data_path: "../raw_eventlogs/BPI_Challenge_2019.xes"
    is_remote: false
    data_owner: "Boudewijn van Dongen"
  - name: "bpi_2017"
    dataset_normalizer: "BPI2017Normalizer"
    dataset_loader: "LocalXes"
    data_path: "../raw_eventlogs/BPI Challenge 2017.xes/BPI Challenge 2017.xes"
    is_remote: false
    data_owner: "Boudewijn van Dongen"
  - name: "bpi_2015_1"
    dataset_normalizer: "BPI2015Normalizer"
    dataset_loader: "LocalXes"
    data_path: "../raw_eventlogs/BPIC15_1.xes"
    is_remote: false
    data_owner: "Boudewijn van Dongen"
  - name: "bpi_2015_2"
    dataset_normalizer: "BPI2015Normalizer"
    dataset_loader: "LocalXes"
    data_path: "../raw_eventlogs/BPIC15_2.xes"
    is_remote: false
    data_owner: "Boudewijn van Dongen"
  - name: "bpi_2015_3"
    dataset_normalizer: "BPI2015Normalizer"
    dataset_loader: "LocalXes"
    data_path: "../raw_eventlogs/BPIC15_3.xes"
    is_remote: false
    data_owner: "Boudewijn van Dongen"
  - name: "bpi_2015_4"
    dataset_normalizer: "BPI2015Normalizer"
    dataset_loader: "LocalXes"
    data_path: "../raw_eventlogs/BPIC15_4.xes"
    is_remote: false
    data_owner: "Boudewijn van Dongen"
  - name: "bpi_2015_5"
    dataset_normalizer: "BPI2015Normalizer"
    dataset_loader: "LocalXes"
    data_path: "../raw_eventlogs/BPIC15_5.xes"
    is_remote: false
    data_owner: "Boudewijn van Dongen"
  - name: "bpi_2012"
    dataset_normalizer: "BPI2012Normalizer"
    dataset_loader: "LocalXes"
    data_path: "../raw_eventlogs/BPI_Challenge_2012.xes/BPI_Challenge_2012.xes"
    is_remote: false
    data_owner: "Boudewijn van Dongen"
  - name: "bpi_2016"
    dataset_normalizer: "BPI2016Normalizer"
    dataset_loader: "LocalXes"
    data_path: ""
    is_remote: false
    data_owner: "Marcus Dees & Boudewijn van Dongen"
  - name: "bpi_2020_domestic"
    dataset_normalizer: "BPI2020Normalizer"
    dataset_loader: "LocalXes"
    data_path: "../raw_eventlogs/BPI_Challenge_2020_DomesticDeclarations.xes/DomesticDeclarations.xes"
    is_remote: false
    data_owner: "Boudewijn van Dongen"
  - name: "bpi_2020_international"
    dataset_normalizer: "BPI2020Normalizer"
    dataset_loader: "LocalXes"
    data_path: "../raw_eventlogs/BPI_Challenge_2020_InternationalDeclarations.xes/InternationalDeclarations.xes"
    is_remote: false
    data_owner: "Boudewijn van Dongen"
  - name: "bpi_2020_travel_cost"
    dataset_normalizer: "BPI2020Normalizer"
    dataset_loader: "LocalXes"
    data_path: "../raw_eventlogs/BPI_Challenge_2020_PrepaidTravelCost.xes/PrepaidTravelCost.xes"
    is_remote: false
    data_owner: "Boudewijn van Dongen"
  - name: "bpi_2020_rfp"
    dataset_normalizer: "BPI2020Normalizer"
    dataset_loader: "LocalXes"
    data_path: "../raw_eventlogs/BPI_Challenge_2020_RequestForPayment.xes/RequestForPayment.xes"
    is_remote: false
    data_owner: "Boudewijn van Dongen"
  - name: "bpi_2020_permits"
    dataset_normalizer: "BPI2020Normalizer"
    dataset_loader: "LocalXes"
    data_path: "../raw_eventlogs/BPI_Challenge_2020_PermitLog.xes/PermitLog.xes"
    is_remote: false
    data_owner: "Boudewijn van Dongen"
  - name: "bpi_2014"
    dataset_normalizer: "BPI2020Normalizer"
    dataset_loader: "LocalCSV"
    data_path: "'../raw_eventlogs/BPI_Challenge_2014_Detail_Incident_Activity.csv'"
    is_remote: false
    data_owner: "Boudewijn van Dongen"