datasets:
  - name: "bpi_2015_1"
    dataset_normalizer: "BPI2015Normalizer"
    dataset_loader: "LocalXes"
    data_path: "../../raw_eventlogs/BPIC15_1.xes"
    is_remote: false
    data_owner: "Boudewijn van Dongen"
    tasks:
      - name: "bpi_2015_1_remaining_time"
    split_details:
      start_date: "2010-10"
      end_date: "2015-03"
      max_days: 302.82
  - name: "bpi_2015_2"
    dataset_normalizer: "BPI2015Normalizer"
    dataset_loader: "LocalXes"
    data_path: "../../raw_eventlogs/BPIC15_2.xes"
    is_remote: false
    data_owner: "Boudewijn van Dongen"
    tasks:
      - name: "bpi_2015_2_remaining_time"
    split_details:
      start_date: "2010-10"
      end_date: "2015-03"
      max_days: 302.82


benchmark:
    task_type: "outcome"
    name: "Test Benchmark"
    save_folder: "outcome_regression"
    attr_col: null
    keywords_dict: {"REMAINING_TIME": "REMAINING_TIME"}
    evaluator: "OutcomeRegression"

    tasks:
      - name: "bpi_2015_1_remaining_time"
        save_folder: "outcome_regression/bpi_2015_1_remaining_time_task"
        task_generator:
          name: "OutcomeRegression"
      - name: "bpi_2015_2_remaining_time"
        save_folder: "outcome_regression/bpi_2015_2_remaining_time_task"
        task_generator:
          name: "OutcomeRegression"
    metrics:
      - name: "MAE"
      - name: "RMSE"
      - name: "MSE"
      - name: "Correlation"